bookmark/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns= [
    path('', show, name= "show"),
    path('new/', new, name= "new"),
    path('edit/<int:pk>', edit, name= "edit"),
    path('delete/<int:pk>', delete, name= "delete"),
]

main/models.py
from django.db import models

# Create your models here.

class Bookmark(models.Model):
    site_name = models.CharField(max_length=50)
    site_url = models.CharField(max_length=1000)

main/forms.py
from django import forms
from .models import Bookmark

class BookmarkForm(forms.ModelForm):
    site_name = forms.CharField(label="사이트명")
    site_url = forms.CharField(label="사이트 주소")


    class Meta:
        model = Bookmark
        fields = '__all__'

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Bookmark
from .forms import BookmarkForm
from django.core.paginator import Paginator

# Create your views here.

def show(request):
    bookmark = Bookmark.objects
    bookmarks = Bookmark.objects.all()
    paginator = Paginator(bookmarks, 2)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    return render(request, 'show.html', {'bookmarks':bookmarks, 'posts':posts})

def new(request):

    if request.method=='POST':
        form = BookmarkForm(request.POST)
        if form.is_valid():
            bookmark = Bookmark()
            bookmark.site_name = form.cleaned_data['site_name']
            bookmark.site_url = form.cleaned_data['site_url']
            bookmark.save()
            return redirect('main:show')

    else:
        form = BookmarkForm()

    return render(request, 'new.html', {'form':form})


def edit(request,pk):

    bookmark = get_object_or_404(Bookmark, pk=pk)

    if request.method=='POST':
        form = BookmarkForm(request.POST, instance=bookmark)
        if form.is_valid():
            bookmark.site_name = form.cleaned_data['site_name']
            bookmark.site_url = form.cleaned_data['site_url']
            bookmark.save()
            return redirect('main:show')

    else:
        form = BookmarkForm(instance=bookmark)

    return render(request, 'new.html', {'bookmark':bookmark, 'form':form})


def delete(request, pk):

    bookmark = get_object_or_404(Bookmark, pk=pk)

    if request.method=='POST':
        bookmark.delete()
        return redirect('main:show')

bookmark/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BOOKMARK</title>
    {% load static %}
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head %}

    {% endblock %}
</head>
<body>
    {% block content %}

    {% endblock %}

</body>
</html>

main/templates/base.html
{% extends 'base.html' %}

main/templates/edit.html
{% extends 'base.html' %}
{% block head %}

{% endblock %}

{% block content %}

<div>
    <header>BOOK-MARK</header>
    <br>
    <div>
        <button><a href="{% url 'main:show' %}">HOME</a></button>
    </div>
</div>

<div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="수정">
    </form>
</div>


{% endblock %}

main/templates/new.html
{% extends 'base.html' %}
{% block head %}

{% endblock %}

{% block content %}

<div>
    <header>BOOK_MARK</header>
    <br>
    <div>
        <button><a href="{% url 'main:show' %}">HOME</a></button>
    </div>
</div>

<div>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}
        <input type="submit" value="추가">
    </form>
</div>
{% endblock %}

main/templates/show.html
{% extends 'base.html' %}
{% block head %}

{% endblock %}

{% block content %}

<div>
    <header>BOOK_MARK</header>
    <br>
    <div>
        <button><a href="{% url 'main:new' %}">CREATE</a></button>
    </div>
</div>

<div>
    {% if posts %}

    {% for bookmark in posts %}
    <div>
        <p class="se"> {{ bookmark.site_name }}</p>
        <p class="jh">{{ bookmark.site_url }}</p1>
        <div>
            <a href="{% url 'main:edit' bookmark.id %}">edit</a>
            <form action="{% url 'main:delete' bookmark.id %}" method='POST'>
                {% csrf_token %}
                <input type="submit" value="delete">
            </form>
        </div>
<br><br>
    </div>
    {% endfor %}
    {% if posts.has_previous %}
    <a href="?page={{posts.previous_page_number}}">previous</a>
    {% endif %}
    <div style="color: black;" >
    <span>{{ posts.number }}</span>
    <span>/</span>
    <span>{{ posts.paginator.num_pages }}</span>
    {% if posts.has_next %}
    <a href="?page={{posts.next_page_number}}">next</a></div>
    {% endif %}

    {% else %}
    
    <div>
        <p>
            북마크가 비어있어요 CREATE 필요
        </p>
    </div>
    
    {% endif %}


</div>

{% endblock %}